name: docker-compose-actions-workflow
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'DCOS/**'
      - 'K8s/**'
      - 'load-gen/**'
      - 'OpenShift/**'
      - 'Swarm/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Build the stack
        run: docker-compose build
